<a href="https://colab.research.google.com/github/Shrawanpandit/Machine_Learning_Lab-Works/blob/main/MachineLearningLab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
List_name=['science','mathematics','English','Nepali','computer']

In [ ]:
print(List_name)

['science', 'mathematics', 'History', 'Nepali', 'computer']


In [ ]:
# Print the first element of the list
print(f"First element: {List_name[0]}")

First element: science


In [ ]:
# Print the last element of the list
print(f"Last element: {List_name[-1]}")

Last element: computer


In [ ]:
# Replace the third element (index 2) of the list
List_name[2] = 'History'

# Print the updated list to verify the change
print(List_name)

['science', 'mathematics', 'History', 'Nepali', 'computer']


In [ ]:
List_name.append('social')
print(List_name)

['science', 'mathematics', 'History', 'Nepali', 'computer', 'social']


In [ ]:
List_name.insert(2, 'probability')
print(List_name)

['science', 'mathematics', 'probability', 'History', 'Nepali', 'computer', 'social']


In [ ]:
List_name.remove(List_name[2])
print(List_name)

['science', 'mathematics']


In [ ]:
List_name.pop(0)
print(List_name)

[]


In [ ]:
List_name=['science','mathematics','English','Nepali','computer']

In [ ]:
print(List_name)

['science', 'mathematics', 'English', 'Nepali', 'computer']


In [ ]:
List_name.sort()
print(List_name)

['English', 'Nepali', 'computer', 'mathematics', 'science']


In [ ]:
List_name.reverse()
print(List_name)

['English', 'Nepali', 'computer', 'mathematics', 'science']


In [ ]:
number_list = [1, 2, 3, 4, 5]
print(number_list)

[1, 2, 3, 4, 5]


In [ ]:
number_list.extend([6,7])
print(number_list)

[1, 2, 3, 4, 5, 6, 7, 6, 7]


In [ ]:
number_list.pop(0)

1

In [ ]:
print(number_list)

[2, 3, 4, 5, 6, 7, 6, 7]


In [ ]:
number_list.sort()

In [ ]:
print(number_list)

[2, 3, 4, 5, 6, 6, 7, 7]


In [ ]:
number_list.reverse()
print(number_list)

[7, 7, 6, 6, 5, 4, 3, 2]


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
print("Diagonal elements:")
for i in range(len(matrix)):
    print(matrix[i][i])

Diagonal elements:
1
5
9


In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[1,2,3],[4,5,6],[7,8,9]]

### Adding Two Matrices (Element-wise)

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[1,2,3],[4,5,6],[7,8,9]]

result = []
for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        row.append(A[i][j] + B[i][j])
    result.append(row)

print("Matrix A:", A)
print("Matrix B:", B)
print("Sum of A and B:", result)

Matrix A: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Matrix B: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Sum of A and B: [[2, 4, 6], [8, 10, 12], [14, 16, 18]]


In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[1,2,3],[4,5,6],[7,8,9]]
C=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(3):
  for j in range(3):
    for k in range(3):
      C[i][j]+=A[i][k]*B[k][j]

print(C)

[[30, 36, 42], [66, 81, 96], [102, 126, 150]]


In [ ]:
!pip install numpy



In [ ]:
import numpy as np
A=np.array([[1,2,3],
           [4,5,6],
            [7,8,9]])
B=np.array([[9,8,7],
           [6,5,4],
            [3,2,1]])
result=A*B
print("NumPy Result:")
print(result)

NumPy Result:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
